name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # For manual triggering
  schedule:
    - cron: '0 19 * * *' # Runs every day at 19:00 UTC (which is 3 AM GMT+8)

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        headless: true

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-results
        path: cypress/results
